name: GitHub Actions Demo
on: push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: upgrade pakages
        run: sudo apt update && sudo apt upgrade
      - name: Install dependencies
        run: sudo apt install neofetch qemu-utils make git
      - name: Show Infos
        run: neofetch
      - name: Clone repository
        run: git clone https://github.com/thenickdude/OSX-KVM
      - name: List files
        run: ls -lah
      - name: Go into scripts/monterey
        run: cd OSX-KVM/scripts/monterey
      - name: Start build
        run: make Monterey-full.img
      - run: echo "ğŸ This job's status is ${{ job.status }}."
